
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: users_api_development


test:
  <<: *default
  database: users_api_test

production:
  <<: *default
  database: users_api_production
  username: users_api
  password: <%= ENV['USERS_API_DATABASE_PASSWORD'] %>
